{
 "title": "Azure / Insights / Data Explorer Clusters",
 "description": "The dashboard provides insights of Azure Data Explorer Cluster Resource overview, key mettrics, usage, tables, cache and ingestion.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   { "name": "ns", "label": "Namespace", "query": "Microsoft.Kusto/clusters" },
   {
    "name": "resource",
    "label": "Resource",
    "query": {}
   },
   {
    "name": "ws",
    "label": "Workspace",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Keep Alive (Avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "KeepAlive",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU (Avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "CPU",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion Utilization (Avg)  ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "IngestionUtilization",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion Latency (Avg)  ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "IngestionLatencyInSeconds",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Cache Utilization (Avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "CacheUtilization",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Succeeded Ingestions (#)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Status", "value": "IngestionResultDetails" }
      ],
      "metricDefinition": "$ns",
      "metricName": "IngestionResult",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top resource consumers",
   "type": "table",
   "description": "The aggregated usage in the cluster, out of the total used CPU and memory. To see more details, go to the Usage tab.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is KustoRunner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand \n    | where TimeGenerated > datetime(2020-09-09T09:30:00Z) \n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak) \n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State, FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest'\n    //| where totimespan(TotalCPU) > totimespan(0)\n    | summarize TotalCPU=max(TotalCPU) \n        , MemoryPeak=max(MemoryPeak)\n        by User, ApplicationName, CorrelationId \n;\r\nlet totalCPU = toscalar(dataset\n    | summarize sum((totimespan(TotalCPU) / 1s)));\r\nlet totalMemory = toscalar(dataset\n    | summarize sum(MemoryPeak));\r\nlet topMemory = \n    dataset\n    | top-nested 10000 of User with others=\"Others\" by sum(MemoryPeak), top-nested 10000 of ApplicationName with others=\"Others\" by sum(MemoryPeak)\n    | extend PercentOfTotalClusterMemoryUsed = aggregated_ApplicationName / toreal(totalMemory)\n;\r\nlet topCpu = \n    dataset\n    | top-nested 10000 of User with others=\"Others\" by sum(totimespan(TotalCPU) / 1s), top-nested 10000 of ApplicationName with others=\"Others\" by sum(totimespan(TotalCPU) / 1s)\n    | extend PercentOfTotalClusterCpuUsed = aggregated_ApplicationName / toreal(totalCPU)\n;\r\ntopMemory\n| join kind = fullouter(topCpu) on User, ApplicationName\n| extend BothPercentages = PercentOfTotalClusterMemoryUsed + PercentOfTotalClusterCpuUsed\n| top 10 by BothPercentages desc\n| extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n    ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n    User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n    User)\n| extend PercentOfTotalClusterMemoryUsed_display = iff(isnan(PercentOfTotalClusterMemoryUsed * 100), toreal(0), PercentOfTotalClusterMemoryUsed * 100)\n| extend PercentOfTotalClusterCpuUsed_display = iff(isnan(PercentOfTotalClusterCpuUsed * 100), toreal(0), PercentOfTotalClusterCpuUsed * 100)\n| where not (ApplicationName == \"Others\" and PercentOfTotalClusterMemoryUsed_display == 0 and PercentOfTotalClusterCpuUsed_display == 0)\n| project User, ApplicationName, PercentOfTotalClusterMemoryUsed_display, PercentOfTotalClusterCpuUsed_display",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Unique user count",
   "type": "timeseries",
   "description": "Over a sliding timeline window. Not affected by the time range parameter",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak) \n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ApplicationName != 'Kusto.WinSvc.DM.Svc'\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ApplicationName != 'Kusto.WinSvc.DM.Svc'\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User,\n        ApplicationName,\n        Principal,\n        TotalCPU,\n        MemoryPeak,\n        CorrelationId,\n        cluster_name;\r\nlet raw = dataset_commands_queries\n    | where LastUpdatedOn > ago(7d)\n    | where cluster_name == 'mitulktest'\n    | where StartedOn > ago(365d)\n;\r\nraw\n| evaluate activity_engagement(User, StartedOn, 1d, 7d)\n| join kind = inner (\n    raw\n    | evaluate activity_engagement(User, StartedOn, 1d, 30d)\n    )\n    on StartedOn\n| project StartedOn, Daily=dcount_activities_inner, Weekly=dcount_activities_outer, Monthly = dcount_activities_outer1     \n| where StartedOn > ago(90d)\n| project Daily, StartedOn, Weekly, Monthly\n| sort by StartedOn asc\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Key Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Keep Alive",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "KeepAlive",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "CPU",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Cache Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "CacheUtilization",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "InstanceCount",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Concurrent Queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "TotalNumberOfConcurrentQueries",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum",
       "Total"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Query Status", "value": "QueryStatus" }
      ],
      "metricDefinition": "$ns",
      "metricName": "QueryDuration",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttled Commands",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum",
       "Total"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Command Type", "value": "CommandType" }
      ],
      "metricDefinition": "$ns",
      "metricName": "TotalNumberOfThrottledCommands",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttled Queries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum",
       "Total"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "TotalNumberOfThrottledQueries",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "IngestionUtilization",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "IngestionLatencyInSeconds",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion Result",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Status", "value": "IngestionResultDetails" }
      ],
      "metricDefinition": "$ns",
      "metricName": "IngestionResult",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion Volume",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Database", "value": "Database" }
      ],
      "metricDefinition": "$ns",
      "metricName": "IngestionVolumeInMB",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Streaming Ingest Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "StreamingIngestDataRate",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Streaming Ingest Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "StreamingIngestDuration",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Streaming Ingest Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "None",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$ns",
      "metricName": "SteamingIngestRequestRate",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Streaming Ingest Result",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Result", "value": "Result" }
      ],
      "metricDefinition": "$ns",
      "metricName": "StreamingIngestResults",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Events Processed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "EventsProcessed",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Discovery Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top resource consumers (within the CPU and memory consumption of the cluster)",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 66 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is KustoRunner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand \n    | where TimeGenerated > datetime(2020-09-09T09:30:00Z) \n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak) \n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State, FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest'\n    //| where totimespan(TotalCPU) > totimespan(0)\n    | summarize TotalCPU=max(TotalCPU) \n        , MemoryPeak=max(MemoryPeak)\n        by User, ApplicationName, CorrelationId \n;\r\nlet totalCPU = toscalar(dataset\n    | summarize sum((totimespan(TotalCPU) / 1s)));\r\nlet totalMemory = toscalar(dataset\n    | summarize sum(MemoryPeak));\r\nlet topMemory = \n    dataset\n    | top-nested 10000 of User with others=\"Others\" by sum(MemoryPeak), top-nested 10000 of ApplicationName with others=\"Others\" by sum(MemoryPeak)\n    | extend PercentOfTotalClusterMemoryUsed = aggregated_ApplicationName / toreal(totalMemory)\n;\r\nlet topCpu = \n    dataset\n    | top-nested 10000 of User with others=\"Others\" by sum(totimespan(TotalCPU) / 1s), top-nested 10000 of ApplicationName with others=\"Others\" by sum(totimespan(TotalCPU) / 1s)\n    | extend PercentOfTotalClusterCpuUsed = aggregated_ApplicationName / toreal(totalCPU)\n;\r\ntopMemory\n| join kind = fullouter(topCpu) on User, ApplicationName\n| extend BothPercentages = PercentOfTotalClusterMemoryUsed + PercentOfTotalClusterCpuUsed\n| top 10 by BothPercentages desc\n| extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n    ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n    User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n    User)\n| extend PercentOfTotalClusterMemoryUsed_display = iff(isnan(PercentOfTotalClusterMemoryUsed * 100), toreal(0), PercentOfTotalClusterMemoryUsed * 100)\n| extend PercentOfTotalClusterCpuUsed_display = iff(isnan(PercentOfTotalClusterCpuUsed * 100), toreal(0), PercentOfTotalClusterCpuUsed * 100)\n| where not (ApplicationName == \"Others\" and PercentOfTotalClusterMemoryUsed_display == 0 and PercentOfTotalClusterCpuUsed_display == 0)\n| project User, ApplicationName, PercentOfTotalClusterMemoryUsed_display, PercentOfTotalClusterCpuUsed_display",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top principals and applications by command and query count",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 66 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest'\n    | where CommandType != 'TableSetOrAppend'\n    | summarize Count=count() by User, ApplicationName\n    | project User, ApplicationName, Count\n    | extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n        User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters\n        User)\n    | top 10 by Count;\n//| order by Count desc\n// <Option #1 for top-nested> | top-nested 10 of User with others=\"Other Values\" by agg_User=sum(Count) desc;\n// <Option #2 for top-nested>| top-nested 10 of User by agg_User=sum(Count) desc, top-nested 5 of ApplicationName with others=\"Other applications\" by agg_App=sum(Count) desc\n// <Option #2 for top-nested>| where not (ApplicationName == \"Other applications\" and agg_App == 0)\n// <Option #2 for top-nested>| project-away agg_User;\r\ndataset\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top applications by command and query count",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is KustoRunner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\",\n        ApplicationName)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest'\n    | where CommandType != 'TableSetOrAppend'\n    | summarize Count=count() by ApplicationName\n    | project ApplicationName, Count\n    | order by Count desc\n    //| top-nested 10 of User with others=\"Other Values\" by agg_User=sum(Count) desc;\n    | top-nested 7 of ApplicationName with others=\"Other Values\"  by agg_App=sum(Count) desc;\n//|where not (ApplicationName == \"Other applications\" and agg_App == 0)\n//|project-away agg_User;\r\ndataset\n",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top principals by command and query count",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 70 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is KustoRunner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest'\n    | where CommandType != 'TableSetOrAppend'\n    | extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n        ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n        User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n        User)\n    | summarize Count=count() by User\n    | project User, Count\n    | order by Count desc\n    | top-nested 7 of User with others=\"Other Values\" by agg_User=sum(Count) desc;\r\ndataset\n\n",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Queries and top commands by command type",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 70 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is KustoRunner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest'\n    | where CommandType != 'TableSetOrAppend'\n    | summarize Count=count() by CommandType\n    | project CommandType, Count\n    | order by Count desc\n    | top-nested 7 of CommandType with others=\"Other Values\"  by agg_App=sum(Count) desc;\r\ndataset\n",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Changes in query count by principal (not affected by the the time range parameter)",
   "type": "table",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 75 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is KustoRunner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | where TimeGenerated > ago(17d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where TimeGenerated > ago(17d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend';\r\nlet Last24Hours =\n    FullList\n    | where StartedOn >= ago(1d) and StartedOn < now()\n    | summarize Count=count() by User, ApplicationName\n    | top 100 by Count desc\n;\r\nlet HistoricalDailyAverage =\n    FullList\n    | where StartedOn >= ago(16d) and StartedOn < ago(1d)\n    | summarize Count=count() / 15.0 by User, ApplicationName\n    | top 100 by Count desc\n;\r\nlet TimeRangeComparison =\n    Last24Hours\n    | join kind=leftouter (HistoricalDailyAverage) on User, ApplicationName\n    | project User=coalesce(User, User1), ApplicationName, Last24Hours=Count, HistoricalDailyAverage=round(Count1, 0)\n    | extend PercentChange=round((Last24Hours - HistoricalDailyAverage) / toreal(HistoricalDailyAverage), 2)\n    | top 10 by Last24Hours desc\n;\r\nTimeRangeComparison\n| extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n    ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n    User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n    User)\n| project User, ApplicationName, HistoricalDailyAverage=round(HistoricalDailyAverage, 0), Last24Hours, PercentChange\n| order by Last24Hours desc",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failed queries",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 75 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Quert Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where LastUpdatedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\ndataset\n| where CommandType != 'TableSetOrAppend' and State == 'Failed'\n| summarize Count=count() by User, ApplicationName\n| top 10 by Count desc\n| extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n    ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n    User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n    User)\n| order by Count desc\n",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Command + query count by principal",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend'\n    | project User, StartedOn, ApplicationName, CommandType\n;\r\nlet Top =\n    dataset\n    | summarize Count=count() by User\n    | top 10 by Count desc\n    | extend OriginalUser = User\n    | extend Category=User\n;\r\nFullList\n| join kind=leftouter(Top) on $left.User == $right.OriginalUser\n| project User=coalesce(Category, 'Other'), ApplicationName, CommandType, StartedOn\n| extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n    ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n    User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n    User)\n| summarize count() by User, bin(StartedOn, 1h)\n| summarize sum(count_) by bin(StartedOn, 1h), tostring(User)\n| sort by StartedOn asc",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total memory by principal",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend'\n    | project User, ApplicationName, CommandType, StartedOn, MemoryPeak\n    | extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n        ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n        User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n        User)\n;\r\nlet Top =\n    FullList\n    | summarize Memory=sum(MemoryPeak) by User\n    | top 10 by Memory desc\n    | extend OriginalUser = User\n    | project OriginalUser, Category=User\n;\r\nFullList\n| join kind=leftouter(Top) on $left.User == $right.OriginalUser\n| project User=coalesce(Category, 'Other'), StartedOn, MemoryPeakGB=MemoryPeak / 1024.0 / 1024.0 / 1024.0\n| summarize MemoryPeakGB=sum(MemoryPeakGB) by User, bin(StartedOn, 1h)\n| summarize sum(MemoryPeakGB) by bin(StartedOn, 1h), tostring(User)\n| sort by StartedOn asc",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total CPU by principal",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where StartedOn > ago(7d)\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend'\n    | project User, ApplicationName, CommandType, StartedOn, TotalCPU\n    | extend User = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", strcat(\"Kusto Data Management \", \"(\", User, \")\"),\n        ApplicationName == \"KustoQueryRunner\", strcat(\"Kusto Query Runner \", \"(\", User, \")\"),\n        User == \"AAD app id=e0331ea9-83fc-4409-a17d-6375364c3280\", \"DataMap Agent 001 (app id: e0331ea9-83fc-4409-a17d-6375364c3280)\", // Used for internal MS clusters \n        User)\n;\r\nlet Top =\n    FullList\n    | summarize TotalCpu=sum(totimespan(TotalCPU)) by User\n    | top 10 by TotalCpu desc\n    | extend OriginalUser = User\n    | project OriginalUser, Category=User\n;\r\nFullList\n| join kind=leftouter(Top) on $left.User == $right.OriginalUser\n| project User=coalesce(Category, 'Other'), StartedOn, TotalCpuMinutes=totimespan(TotalCPU) / 1m\n| summarize TotalCpuMinutes=sum(TotalCpuMinutes) by User, bin(StartedOn, 1h)\n| top-nested of bin(StartedOn, 1h) by sum(TotalCpuMinutes), top-nested 5 of User with others=\"Other Values\" by sum_TotalCpuMinutes=sum(TotalCpuMinutes) desc\n| sort by StartedOn asc\n| project StartedOn, User, sum_TotalCpuMinutes\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Command + query count by application",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\", ApplicationName)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend'\n    | project ApplicationName, StartedOn, CommandType, User\n;\r\nlet Top =\n    FullList\n    | summarize Count=count() by ApplicationName\n    | top 10 by Count desc\n    | extend Category=ApplicationName\n;\r\nFullList\n| join kind=leftouter(Top) on ApplicationName \n| project Application=coalesce(Category, '-'), CommandType, User, StartedOn\n| summarize count() by Application, bin(StartedOn, 1h)\n| summarize sum(count_) by bin(StartedOn, time(1h)), tostring(Application)\n| sort by StartedOn asc\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total memory by application",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak) \n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\", ApplicationName)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend'\n    | project ApplicationName, StartedOn, CommandType, User, MemoryPeak\n;\r\nlet Top =\n    FullList\n    | summarize Memory=sum(MemoryPeak) by ApplicationName\n    | top 10 by Memory desc\n    | extend Category=ApplicationName;\r\nFullList\n| join kind=inner(Top) on ApplicationName\n| project Application=coalesce(Category, '-'), CommandType, User, StartedOn, MemoryPeakMB=MemoryPeak / 1024.0 / 1024.0\n| summarize MemoryPeakMB=sum(MemoryPeakMB) by Application, bin(StartedOn, 1h)\n| summarize sum(MemoryPeakMB) by bin(StartedOn, time(1h)), tostring(Application)\n| sort by StartedOn asc\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total CPU by application",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\", ApplicationName)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\nlet FullList = dataset\n    | where CommandType != 'TableSetOrAppend'\n    | project ApplicationName, CommandType, User, StartedOn, TotalCPU\n;\r\nlet Top =\n    FullList\n    | summarize TotalCPU=sum(totimespan(TotalCPU)) by ApplicationName\n    | top 10 by TotalCPU desc\n    | extend Category=ApplicationName\n;\r\nFullList\n| join kind=inner(Top) on ApplicationName\n| project Application=coalesce(Category, '-'), CommandType, User, StartedOn, TotalCpuMinutes=totimespan(TotalCPU) / 1m\n| summarize TotalCpuMinutes=sum(TotalCpuMinutes) by Application, bin(StartedOn, 1h)\n| summarize sum(TotalCpuMinutes) by bin(StartedOn, time(1h)), tostring(Application)\n| sort by StartedOn asc\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Queries + command count by type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\ndataset\n| where CommandType != 'TableSetOrAppend' \n| top-nested of bin(StartedOn, time(1h)) by count(), top-nested 5 of CommandType by count_=count() desc\n| sort by StartedOn asc\n| project StartedOn, CommandType, count_\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total memory by type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak) \n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\ndataset\n| where CommandType != 'TableSetOrAppend' \n| extend MemoryPeakGB=MemoryPeak / 1024.0 / 1024.0 / 1024.0\n| top-nested of bin(StartedOn, time(1h)) by sum(MemoryPeakGB), top-nested 5 of CommandType with others=\"Other Values\" by sum_MemoryPeakGB=sum(MemoryPeakGB) desc\n| sort by StartedOn asc\n| project StartedOn, CommandType, sum_MemoryPeakGB\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total CPU by type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet CommandTable = ADXCommand\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak) \n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | project-away ResourceUtilization;\r\nlet QueryTable = ADXQuery\n    | where StartedOn > ago(7d)\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | extend MemoryPeak = tolong(MemoryPeak)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | extend CommandType = 'Query';\r\nlet dataset_commands_queries = CommandTable\n    | union (QueryTable)\n    | project CommandType, DatabaseName, StartedOn, LastUpdatedOn, Duration, State,\n        FailureReason, RootActivityId, User, ApplicationName, Principal, TotalCPU, MemoryPeak, CorrelationId, cluster_name;\r\nlet dataset = dataset_commands_queries\n    | where cluster_name == 'mitulktest';\r\ndataset\n| where CommandType != 'TableSetOrAppend' \n| extend TotalCpuMinutes = totimespan(TotalCPU) / 1m\n| top-nested of bin(StartedOn, time(1h)) by sum(TotalCpuMinutes), top-nested 5 of CommandType with others=\"Other Values\" by sum_TotalCpuMinutes=sum(TotalCpuMinutes) desc\n| sort by StartedOn asc\n| project StartedOn, CommandType, sum_TotalCpuMinutes\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Command + query count by workload group",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 109 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet commandTable = \n    ADXCommand \n    | where StartedOn > ago(7d)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | project User, StartedOn, ApplicationName, CommandType, WorkloadGroup\n;\r\nlet queryTable = \n    ADXQuery \n    | where StartedOn > ago(7d)\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | extend CommandType = 'Query'\n    | project User, StartedOn, ApplicationName, CommandType, WorkloadGroup;\r\nlet FullList = commandTable\n    | union (queryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\", ApplicationName)\n    | project User, StartedOn, ApplicationName, CommandType, WorkloadGroup;\r\nlet Top =\n    FullList\n    | summarize Count=count() by WorkloadGroup\n    | top 10 by Count desc\n    | distinct WorkloadGroup\n;\r\nFullList\n| project WorkloadGroup = iff((WorkloadGroup in(Top)) == true, WorkloadGroup, 'Other'), CommandType, StartedOn\n| make-series count() on StartedOn from ago(7d) to now() step 1h by WorkloadGroup\n",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total memory by workload group",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 109 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet commandTable = \n    ADXCommand\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where StartedOn > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | extend MemoryPeak = tolong(ResourceUtilization.MemoryPeak)\n    | project User, ApplicationName, CommandType, StartedOn, MemoryPeak, WorkloadGroup\n;\r\nlet queryTable = \n    ADXQuery \n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where StartedOn > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | extend CommandType = 'Query'\n    | project User, ApplicationName, CommandType, StartedOn, MemoryPeak, WorkloadGroup;\r\nlet FullList = commandTable\n    | union (queryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\", ApplicationName)\n    | project User, ApplicationName, CommandType, StartedOn, MemoryPeak, WorkloadGroup;\r\nlet Top =\n    FullList\n    | summarize Memory=sum(MemoryPeak) by WorkloadGroup\n    | top 10 by Memory desc\n    | distinct WorkloadGroup\n;\r\nFullList\n| project WorkloadGroup = iff((WorkloadGroup in(Top)) == true, WorkloadGroup, 'Other'), CommandType, User, StartedOn, MemoryPeakGB=MemoryPeak / 1024.0 / 1024.0 / 1024.0\n| make-series MemoryPeakGB=sum(MemoryPeakGB) on StartedOn from ago(7d) to now() step 1h by WorkloadGroup",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total CPU by workload group",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 109 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let system_databases = dynamic(['KustoMonitoringPersistentDatabase', '$systemdb']); \r\nlet system_users = dynamic(['AAD app id=b753584e-c468-4503-852a-374280ce7a62', 'KustoServiceBuiltInPrincipal']); // b753584e-c468-4503-852a-374280ce7a62 is Kusto Query Runner\r\nlet system_cluster_management_applications = dynamic(['Kusto.WinSvc.CM.Svc']); // Kusto Cluster Management\r\nlet commandTable = \n    ADXCommand\n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where StartedOn > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | project User, ApplicationName, CommandType, StartedOn, TotalCPU, WorkloadGroup\n;\r\nlet queryTable = \n    ADXQuery \n    | where ((false == \"false\" and ApplicationName != 'Kusto.WinSvc.DM.Svc') or false == \"true\")\n    | where DatabaseName !in (system_databases) and User !in (system_users) and ApplicationName !in (system_cluster_management_applications)\n    | where StartedOn > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | extend CommandType = 'Query'\n    | project User, ApplicationName, CommandType, StartedOn, TotalCPU, WorkloadGroup;\r\nlet FullList = commandTable\n    | union (queryTable)\n    | extend ApplicationName = case(ApplicationName == \"Kusto.WinSvc.DM.Svc\", \"Kusto Data Management\", ApplicationName)\n    | project User, ApplicationName, CommandType, StartedOn, totimespan(TotalCPU), WorkloadGroup;\r\nlet Top =\n    FullList\n    | summarize TotalCpu=sum(TotalCPU) by WorkloadGroup\n    | top 10 by TotalCpu desc\n    | distinct WorkloadGroup\n;\r\nFullList\n| project WorkloadGroup = iff((WorkloadGroup in(Top)) == true, WorkloadGroup, 'Other'), StartedOn, TotalCpuMinutes=totimespan(TotalCPU) / 1m\n| make-series TotalCpuMinutes=sum(TotalCpuMinutes) on StartedOn from ago(7d) to now() step 1h by WorkloadGroup",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {}
   ]
  },
  {
   "title": "  Table details",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "ADXTableDetails \n| where TimeGenerated >= ago(1d)\n| project TimeGenerated,\n    DatabaseName,\n    TableName,\n    RetentionPolicyOrigin,\n    CachingPolicyOrigin,\n    OriginalSize = TotalOriginalSize, \n    TotalExtentSize, \n    HotExtentSize = HotExtentSize, \n    RowCount = TotalRowCount, \n    ExtentCount = TotalExtentCount,\n    SoftDelete = format_timespan(totimespan(todynamic(RetentionPolicy).SoftDeletePeriod), 'd'),\n    HotCache = format_timespan(totimespan(todynamic(CachingPolicy).DataHotSpan), 'd')      \n| extend CompressionRatio = round(toreal(OriginalSize) / TotalExtentSize, 1)\n| extend SoftDelete = iff(RetentionPolicyOrigin == \"default\" and isempty(SoftDelete), \"unlimited\", SoftDelete)\n| extend HotCache = iff(CachingPolicyOrigin == \"default\" and isempty(HotCache), \"unlimited\", HotCache)\n| summarize arg_max(TimeGenerated, *) by DatabaseName, TableName\n| top 351 by HotExtentSize desc\n| project DatabaseName,\n    TableName,\n    RowCount, \n    HotExtentSize,\n    SoftDelete,\n    HotCache,\n    OriginalSize, \n    TotalExtentSize,\n    CompressionRatio, \n    ExtentCount\n",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top tables by row count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let TotalRowCountTable = ADXTableDetails\n    | where TimeGenerated > ago(7d)\n    | project Time = TimeGenerated, Category = strcat(TableName, \" (DB: \", DatabaseName, \")\"), Value = toreal(TotalRowCount);\r\nlet topCategories = \n    TotalRowCountTable\n    | summarize sum(Value) by Category\n    | top 9 by sum_Value desc\n;\r\nTotalRowCountTable\n| join kind = leftouter (topCategories) on Category\n| project Category = coalesce(Category1, 'Other Tables'), Value, Time\n| summarize max(Value) by Category, bin(Time, 1h)\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top tables by hot cache size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let HotExtentSizeTable = ADXTableDetails\n    | where TimeGenerated > ago(7d)\n    | project Time = TimeGenerated, Category = strcat(TableName, \" (DB: \", DatabaseName, \")\"), Value = HotExtentSize;\r\nlet topCategories = \n    HotExtentSizeTable\n    | summarize sum(Value) by Category\n    | top 9 by sum_Value desc;\r\nHotExtentSizeTable\n| join kind = leftouter (topCategories) on Category\n| project Category = coalesce(Category1, 'Other Tables'), Value, Time\n| summarize max(Value) by Category, bin(Time, 1h)\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top tables by extent count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let TotalExtentCountTable = ADXTableDetails\n    | where TimeGenerated > ago(7d)\n    | project Time = TimeGenerated, Category = strcat(TableName, \" (DB: \", DatabaseName, \")\"), Value = toreal(TotalExtentCount);\r\nlet topCategories = \n    TotalExtentCountTable\n    | summarize sum(Value) by Category\n    | top 9 by sum_Value desc\n;\r\nTotalExtentCountTable\n| join kind = leftouter (topCategories) on Category\n| project Category = coalesce(Category1, 'Other Tables'), Value, Time\n| summarize max(Value) by Category, bin(Time, 1h)\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top tables by extent size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "let TotalExtentSizeTable = ADXTableDetails\n    | where TimeGenerated > ago(7d)\n    | project Time = TimeGenerated, Category = strcat(TableName, \" (DB: \", DatabaseName, \")\"), Value = TotalExtentSize;\r\nlet topCategories = \n    TotalExtentSizeTable\n    | summarize sum(Value) by Category\n    | top 9 by sum_Value desc;\r\nTotalExtentSizeTable\n| join kind = leftouter (topCategories) on Category\n| project Category = coalesce(Category1, 'Other Tables'), Value, Time\n| summarize max(Value) by Category, bin(Time, 1h)\n",
      "resources": [ "$ws" ],
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Table usage details",
   "type": "table",
   "description": "This page presents data based on the Time Range parameter. You can change the Time Range parameter to present data starting from 05/25/21 ,11:38 PM (based on your oldest diagnostic logs data).\n  The table names and the Cache policy column refreshes every 8 hours.\n  Notice the queries statistics presented are based only on queries that scanned data. For instance queries that failed, and queries with time operator of future don't scan any data therefore would not be part of the queries statistics presented.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let TableUsageStatsWithLookBack = ADXTableUsageStatistics\n    | where TimeGenerated > ago(7d)\n    | extend LookBackPeriod = datetime_diff('day', StartedOn, MinCreatedOn) \n    | summarize CountQueries=count() by DatabaseName, TableName, LookBackPeriod;\r\nlet sumAllQueries = TableUsageStatsWithLookBack\n    | summarize sumQueries=sum(CountQueries) by DatabaseName, TableName;\r\nlet percentileLookBackTable= TableUsageStatsWithLookBack\n    | summarize percentile_LookbackDuration_ = percentilesw(LookBackPeriod, CountQueries, 95) by DatabaseName, TableName;\r\nlet defaultRetention = 365d * 10;\r\nADXTableDetails \n| where TimeGenerated >= ago(1d) // so we filter out tables that are deprecated\n| summarize arg_max(TimeGenerated, *) by DatabaseName, TableName\n| extend RetentionPolicy = iff(isnull(RetentionPolicy) or RetentionPolicy == \"null\", defaultRetention, totimespan(parse_json(tostring(RetentionPolicy)).SoftDeletePeriod)),\n    CachingPolicy = iff(isnull(CachingPolicy) or RetentionPolicy == \"null\", defaultRetention, totimespan(parse_json(tostring(CachingPolicy)).DataHotSpan))\n| extend ActiveCachingPolicy = min_of(CachingPolicy, RetentionPolicy)\n| join kind = leftouter (percentileLookBackTable) on DatabaseName, TableName\n| join kind = leftouter (sumAllQueries) on DatabaseName, TableName\n| where DatabaseName != \"KustoMonitoringPersistentDatabase\"\n| top 351 by HotExtentSize desc\n| project DatabaseName, TableName, CacheSize = HotExtentSize, format_timespan(ActiveCachingPolicy, 'd'),  \n    sumQueries=sumQueries, QueryPeriod = percentile_LookbackDuration_",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Succeeded ingestions by table",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 143 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//SucceededIngestion\n//| where TimeGenerated > ago(7d)\n//| parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n//| where cluster_name == 'mitulktest'\n//| summarize count=dcount(IngestionSourcePath) by Database, Table\n//| order by ['count'],Database, Table\r\nlet tenant=\n    FailedIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | distinct TenantId\n    | take 1; //choose one tenant as logs are transferred to many tenants which represents workSpace\r\nlet failures = FailedIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | where TenantId == toscalar(tenant)\n    | summarize f_count=count() by Database, Table;\r\nlet tenant_success=\n    SucceededIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | distinct TenantId\n    | take 1; //choose one tenant as logs are transferred to many tenants which represents workSpace\r\nlet success = SucceededIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | where TenantId == toscalar(tenant_success)\n    | summarize s_count=count() by Database, Table;\r\nsuccess\n| join kind=leftouter failures on Database, Table\n| extend f_count = iif(isnull(f_count), 0, f_count)\n| extend s_count = iif(isnull(s_count), 0, s_count)\n| extend overall = iif(isnull(s_count), 0.0, s_count * 100.0 / (s_count + f_count))\n| project Database, Table, s_count, overall\n| order by s_count, Database, Table",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DiscoveryLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Stage latency (accumulative latency)",
   "type": "timeseries",
   "description": "Time from when a message is discovered by Azure Data Explorer, until its content is received by the Engine Storage for processing.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//SucceededIngestion\n//| where TimeGenerated > ago(7d)\n//| parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n//| where cluster_name == 'mitulktest'\n//| summarize count=dcount(IngestionSourcePath) by Database, Table\n//| order by ['count'],Database, Table\r\nlet tenant=\n    FailedIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | distinct TenantId\n    | take 1; //choose one tenant as logs are transferred to many tenants which represents workSpace\r\nlet failures = FailedIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | where TenantId == toscalar(tenant)\n    | summarize f_count=count() by Database, Table;\r\nlet tenant_success=\n    SucceededIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | distinct TenantId\n    | take 1; //choose one tenant as logs are transferred to many tenants which represents workSpace\r\nlet success = SucceededIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | where TenantId == toscalar(tenant_success)\n    | summarize s_count=count() by Database, Table;\r\nsuccess\n| join kind=leftouter failures on Database, Table\n| extend f_count = iif(isnull(f_count), 0, f_count)\n| extend s_count = iif(isnull(s_count), 0, s_count)\n| extend overall = iif(isnull(s_count), 0.0, s_count * 100.0 / (s_count + f_count))\n| project Database, Table, s_count, overall\n| order by s_count, Database, Table",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "ComponentType", "filters": [ "StorageEngine" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Database", "value": "Database" },
       { "text": "Component Type", "value": "ComponentType" }
      ],
      "metricDefinition": "$ns",
      "metricName": "StageLatency",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Data Processed Successfuly",
   "type": "timeseries",
   "description": "Number of blobs processed by the Storage Engine.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//SucceededIngestion\n//| where TimeGenerated > ago(7d)\n//| parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n//| where cluster_name == 'mitulktest'\n//| summarize count=dcount(IngestionSourcePath) by Database, Table\n//| order by ['count'],Database, Table\r\nlet tenant=\n    FailedIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | distinct TenantId\n    | take 1; //choose one tenant as logs are transferred to many tenants which represents workSpace\r\nlet failures = FailedIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | where TenantId == toscalar(tenant)\n    | summarize f_count=count() by Database, Table;\r\nlet tenant_success=\n    SucceededIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | distinct TenantId\n    | take 1; //choose one tenant as logs are transferred to many tenants which represents workSpace\r\nlet success = SucceededIngestion\n    | where TimeGenerated > ago(7d)\n    | parse _ResourceId with * \"providers/microsoft.kusto/clusters/\" cluster_name\n    | where cluster_name == 'mitulktest'\n    | where TenantId == toscalar(tenant_success)\n    | summarize s_count=count() by Database, Table;\r\nsuccess\n| join kind=leftouter failures on Database, Table\n| extend f_count = iif(isnull(f_count), 0, f_count)\n| extend s_count = iif(isnull(s_count), 0, s_count)\n| extend overall = iif(isnull(s_count), 0.0, s_count * 100.0 / (s_count + f_count))\n| project Database, Table, s_count, overall\n| order by s_count, Database, Table",
      "resultFormat": "time_series",
      "workspace": "$ws"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "ComponentType", "filters": [ "StorageEngine" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Database", "value": "Database" },
       { "text": "Component Type", "value": "ComponentType" },
       { "text": "Component Name", "value": "ComponentName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "BlobsProcessed",
      "metricNamespace": "Microsoft.Kusto/clusters",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}