{
 "title": "Azure / Insights / Applications Test Availability Geo Map",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "res",
    "label": "Resource",
    "query": {}
   },
   {
    "name": "reg",
    "label": "Region",
    "query": {}
   },
   {
    "name": "avTest",
    "label": "Availability Test",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"padding: 1em; text-align: center\">\n  <p> This dashboard helps you visualize data on availability tests for your Application Insights. Note that even if you have an App Insights resource configured, if you have no tests configured for it, no data will show. You can configure the following:</p>\n  <ul style=\"display: inline-block; text-align:left\">\n\n      <li>The regions (Select one or more)</li>\n\n      <li>The Availability tests (Select one or more)</li>\n\n      <li>The colors and thresholds in the Geo Maps to make the dashboard more relevant to your environment.</li>\n  </ul>\n</div>"
   }
  },
  {
   "title": "Availability test: ${avTest}",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let regToCoords = dynamic({\n  \"East Asia\":\n    {\n      \"latitude\": 22.267,\n      \"longitude\": 114.188\n    },\n  \"Southeast Asia\":\n    {\n      \"latitude\": 1.283,\n      \"longitude\": 103.833\n    },\n  \"Central US\":\n    {\n      \"latitude\": 41.5908,\n      \"longitude\": -93.6208\n    },\n    \"East US\":\n    {\n      \"latitude\": 37.3719,\n      \"longitude\": -79.8164\n    },\n    \"East US 2\":\n    {\n      \"latitude\": 36.6681,\n      \"longitude\": -78.3889\n    },\n    \"West US\":\n    {\n      \"latitude\": 37.783,\n      \"longitude\": -122.417\n    },\n    \"North Central US\":\n    {\n      \"latitude\": 41.8819,\n      \"longitude\": -87.6278\n    },\n    \"South Central US\":\n    {\n      \"latitude\": 29.4167,\n      \"longitude\": -98.5\n    },\n    \"North Europe\":\n    {\n      \"latitude\": 53.3478,\n      \"longitude\": -6.2597\n    },\n    \"West Europe\":\n    {\n      \"latitude\": 52.3667,\n      \"longitude\": 4.9\n    },\n    \"Japan West\":\n    {\n      \"latitude\": 34.6939,\n      \"longitude\": 135.5022\n    },\n    \"Japan East\":\n    {\n      \"latitude\": 35.68,\n      \"longitude\": 139.77\n    },\n    \"Brazil South\":\n    {\n      \"latitude\": -23.55,\n      \"longitude\": -46.633\n    },\n    \"Australia East\" : \n    {\n    \"latitude\": -33.86, \n    \"longitude\": 151.2094\n    }, \n    \"Australia Southeast\":\n    {\n      \"latitude\": -37.8136,\n      \"longitude\": 144.9631\n    },\n    \"South India\":\n    {\n      \"latitude\": 12.9822,\n      \"longitude\": 80.1636\n    },\n    \"Central India\":\n    {\n      \"latitude\": 18.5822,\n      \"longitude\": 73.9197\n    },\n    \"West India\":\n    {\n      \"latitude\": 19.088,\n      \"longitude\": 72.868\n    },\n    \"Canada Central\":\n    {\n      \"latitude\": 43.653,\n      \"longitude\": -79.383\n    },\n    \"Canada East\":\n    {\n      \"latitude\": 46.817,\n      \"longitude\": -71.217\n    },\n    \"UK South\":\n    {\n      \"latitude\": 50.941,\n      \"longitude\": -0.799\n    },\n  \"UK West\": \n    {\n      \"latitude\": 53.427, \n      \"longitude\": -3.084\n    },\n  \"West Central US\": \n    {\n      \"latitude\": 40.890, \n      \"longitude\": -110.234\n    },\n    \"West US 2\": \n    {\n      \"latitude\": 47.233, \n      \"longitude\": -119.852\n    },\n    \"Korea Central\": \n    {\n      \"latitude\": 37.5665, \n      \"longitude\": 126.9780\n    },\n    \"Korea South\": \n    {\n      \"latitude\": 35.1796, \n      \"longitude\": 129.0756\n    },\n    \"France Central\": \n    {\n      \"latitude\": 46.3772, \n      \"longitude\": 2.3730\n    },\n    \"France South\": \n    {\n      \"latitude\": 43.8345, \n      \"longitude\": 2.1972\n   },\n   \"Australia Central\": \n    {\n      \"latitude\": -35.3075, \n      \"longitude\": 149.1244\n    },\n    \"Australia Central 2\": \n    {\n      \"latitude\": -35.3075, \n      \"longitude\": 149.1244\n    },\n    \"UAE Central\": \n    {\n      \"latitude\": 24.466667, \n      \"longitude\": 54.366669\n    },\n    \"UAE North\": \n    {\n      \"latitude\": 25.266666, \n      \"longitude\": 55.316666\n    },\n    \"South Africa North\": \n    {\n      \"latitude\": -25.731340, \n      \"longitude\": 28.218370\n    },\n    \"South Africa West\": \n    {\n      \"latitude\": -34.075691, \n      \"longitude\": 18.843266\n    }\n});\r\navailabilityResults\n| where timestamp >= $__timeFrom and timestamp < $__timeTo\n| where name in ($avTest) and location in ($reg)\n| extend latitude = tostring(regToCoords[location][\"latitude\"])\n| extend longitude = tostring(regToCoords[location][\"longitude\"])\n| extend percentage = toint(success) * 100\n| summarize avg(percentage) by name, location, latitude, longitude",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
     }
    }
   ]
  },
  {
   "type": "stat",
   "description": "The dashboard provides geographic insights of availability tests on Azure Apps via different metrics for app monitoring through Application Insights.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "availabilityResults\n| where timestamp >= $__timeFrom and timestamp < $__timeTo\n| where name in ($avTest) and success == 1 and location in ($reg)\n| summarize ['avTestResults'] = sum(itemCount) by success",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
     }
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "availabilityResults\n| where timestamp >= $__timeFrom and timestamp < $__timeTo\n| where name in ($avTest) and success == 0 and location in ($reg)\n| summarize ['avTestResults'] = sum(itemCount) by success",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
     }
    }
   ]
  },
  {
   "title": "Availability test : ${avTest}",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "availabilityResults\n| where timestamp > $__timeFrom and timestamp < $__timeTo \n| where true and name in ($avTest)\n| extend percentage = toint(success) * 100\n| summarize avg(percentage) by name, bin(timestamp, 1h)\n| sort by timestamp asc\n| render timechart",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
     }
    }
   ]
  },
  {
   "title": "Availability test results count (Sum)",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 14, "x": 0, "y": 15 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let regToCoords = dynamic({\n  \"East Asia\":\n    {\n      \"latitude\": 22.267,\n      \"longitude\": 114.188\n    },\n  \"Southeast Asia\":\n    {\n      \"latitude\": 1.283,\n      \"longitude\": 103.833\n    },\n  \"Central US\":\n    {\n      \"latitude\": 41.5908,\n      \"longitude\": -93.6208\n    },\n    \"East US\":\n    {\n      \"latitude\": 37.3719,\n      \"longitude\": -79.8164\n    },\n    \"East US 2\":\n    {\n      \"latitude\": 36.6681,\n      \"longitude\": -78.3889\n    },\n    \"West US\":\n    {\n      \"latitude\": 37.783,\n      \"longitude\": -122.417\n    },\n    \"North Central US\":\n    {\n      \"latitude\": 41.8819,\n      \"longitude\": -87.6278\n    },\n    \"South Central US\":\n    {\n      \"latitude\": 29.4167,\n      \"longitude\": -98.5\n    },\n    \"North Europe\":\n    {\n      \"latitude\": 53.3478,\n      \"longitude\": -6.2597\n    },\n    \"West Europe\":\n    {\n      \"latitude\": 52.3667,\n      \"longitude\": 4.9\n    },\n    \"Japan West\":\n    {\n      \"latitude\": 34.6939,\n      \"longitude\": 135.5022\n    },\n    \"Japan East\":\n    {\n      \"latitude\": 35.68,\n      \"longitude\": 139.77\n    },\n    \"Brazil South\":\n    {\n      \"latitude\": -23.55,\n      \"longitude\": -46.633\n    },\n    \"Australia East\" : \n    {\n    \"latitude\": -33.86, \n    \"longitude\": 151.2094\n    }, \n    \"Australia Southeast\":\n    {\n      \"latitude\": -37.8136,\n      \"longitude\": 144.9631\n    },\n    \"South India\":\n    {\n      \"latitude\": 12.9822,\n      \"longitude\": 80.1636\n    },\n    \"Central India\":\n    {\n      \"latitude\": 18.5822,\n      \"longitude\": 73.9197\n    },\n    \"West India\":\n    {\n      \"latitude\": 19.088,\n      \"longitude\": 72.868\n    },\n    \"Canada Central\":\n    {\n      \"latitude\": 43.653,\n      \"longitude\": -79.383\n    },\n    \"Canada East\":\n    {\n      \"latitude\": 46.817,\n      \"longitude\": -71.217\n    },\n    \"UK South\":\n    {\n      \"latitude\": 50.941,\n      \"longitude\": -0.799\n    },\n  \"UK West\": \n    {\n      \"latitude\": 53.427, \n      \"longitude\": -3.084\n    },\n  \"West Central US\": \n    {\n      \"latitude\": 40.890, \n      \"longitude\": -110.234\n    },\n    \"West US 2\": \n    {\n      \"latitude\": 47.233, \n      \"longitude\": -119.852\n    },\n    \"Korea Central\": \n    {\n      \"latitude\": 37.5665, \n      \"longitude\": 126.9780\n    },\n    \"Korea South\": \n    {\n      \"latitude\": 35.1796, \n      \"longitude\": 129.0756\n    },\n    \"France Central\": \n    {\n      \"latitude\": 46.3772, \n      \"longitude\": 2.3730\n    },\n    \"France South\": \n    {\n      \"latitude\": 43.8345, \n      \"longitude\": 2.1972\n   },\n   \"Australia Central\": \n    {\n      \"latitude\": -35.3075, \n      \"longitude\": 149.1244\n    },\n    \"Australia Central 2\": \n    {\n      \"latitude\": -35.3075, \n      \"longitude\": 149.1244\n    },\n    \"UAE Central\": \n    {\n      \"latitude\": 24.466667, \n      \"longitude\": 54.366669\n    },\n    \"UAE North\": \n    {\n      \"latitude\": 25.266666, \n      \"longitude\": 55.316666\n    },\n    \"South Africa North\": \n    {\n      \"latitude\": -25.731340, \n      \"longitude\": 28.218370\n    },\n    \"South Africa West\": \n    {\n      \"latitude\": -34.075691, \n      \"longitude\": 18.843266\n    }\n});\r\navailabilityResults\n| where timestamp >= $__timeFrom and timestamp < $__timeTo and location in ($reg)\n| extend latitude = tostring(regToCoords[location][\"latitude\"])\n| extend longitude = tostring(regToCoords[location][\"longitude\"])\n| extend availabilityResult_duration = iif(itemType == 'availabilityResult', duration, todouble(''))\n| summarize ['avTestResults'] = sum(itemCount) by location, latitude, longitude",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
     }
    }
   ]
  },
  {
   "title": "Test result count by Location",
   "type": "gauge",
   "gridPos": { "h": 15, "w": 10, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "availabilityResults\n| where timestamp >= $__timeFrom and timestamp < $__timeTo and location in ($reg)\n| summarize ['avTestResults'] = sum(itemCount) by location",
      "resource": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
     }
    }
   ]
  }
 ]
}