{
 "title": "Azure / Insights / Applications - Performance - 2. Dependencies",
 "description": "The dashboard provides insights of dependency performance of Azure Apps through Application Insights.",
 "tags": [ "Azure-AppInsights-Perf" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   },
   { "name": "res", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" },
   {
    "name": "dependency",
    "label": "Dependency",
    "query": {}
   },
   {
    "name": "min_duration",
    "label": "Minimum Duration (ms)",
    "query": {}
   },
   {
    "name": "max_duration",
    "label": "Maximum Duration (ms)",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Performance Dependencies" } },
  {
   "title": "Application Insights - Performance - Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Top 3 Dependencies",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\nset truncationmaxrecords=10000;set truncationmaxsize=67108864;set truncationmaxrecords=10000;set truncationmaxsize=67108864;\r\ndependencies\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n| summarize Count=sum(itemCount), AVG_Duration=sum(duration * itemCount)/sum(itemCount), Duration_95th=percentile(duration,95) by type\n| sort by Count desc\n| take 3",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     }
    }
   ]
  },
  {
   "title": "Server Dependencies Response Time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 8 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n// calculate average dependency duration for all dependencies\n| summarize AVG = avg(duration), P95 = percentiles(duration, 95), MAX = max(duration) by bin(timestamp, $__interval)\n| project timestamp, AVG = AVG/1000, P95 = P95/1000, MAX = MAX/1000\n| order by timestamp asc\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Distribution of Server Dependency Response Time (ms)",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n// calculate average request duration for all requests\n| extend ResponseTime = duration/1000\n| project timestamp, ResponseTime\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n// calculate average request duration for all requests\n| summarize Count = count() by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Count of Requests by Server Response Time (sec)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n// calculate average request duration for all requests\n| extend ResponseTime = duration/1000\n| project timestamp, ResponseTime\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "Click on a bar on the chart below to set the minimum and maximum duration. To reset the zoom, change the Minimum Duration and Maximum duration variables."
   }
  },
  {
   "title": "Dependency count by Duration (ms)",
   "type": "barchart",
   "description": "Click on a bar on the chart below to set the minimum and maximum duration. To reset the zoom, change the Minimum Duration and Maximum duration variables.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\n// distribution of dependencies by logarithmic duration buckets\nlet numberOfBuckets = 100;\n// filter to a subset of dependencies\n\nlet dataset = dependencies\n| where client_Type != \"Browser\"\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n| extend value=duration\n| project itemCount, value;\n// calculate the maximum duration for all dependencies\nlet maxValue=toscalar(dataset | summarize max(value));\n// calculate the logarithmic base that determines the start of each bucket\n// use the max duration to ensure the scale spans all possible durations in the data set\nlet bucketBase = pow(maxValue, 1/todouble(numberOfBuckets));\n// define a table with an index for each bucket to allow for buckets with 0 dependencies\nlet bucketSlots=range bucketSlot from 0 to numberOfBuckets - 1 step 1;\n// map dependency counts to the correct bucket and apply to the scale by joining with the complete set of buckets\nbucketSlots | join kind=leftouter (dataset\n// any durations under 1ms are rounded up to 1 ms\n// calls with durations under 1ms can be viewed in more detail using the linear scale\n| extend adjustedValue = iff(value<1, 1.0, value)\n// calculate the bucket slot for each dependency by applying logarithmic scale\n| extend bucketSlotRaw = tolong(bin(log(adjustedValue)/log(bucketBase), 1))\n// calculate the dependency count by duration bucket (rounded to whole number)\n| summarize count_=sum(itemCount) by bucketSlot=iff(bucketSlotRaw > numberOfBuckets - 1, numberOfBuckets - 1, bucketSlotRaw)) on bucketSlot\n| order by bucketSlot asc\n// calculate the real duration value for each bucket based on both the index and the bucket base (rounded to whole number)\n| project\n    [\"Duration (ms)\"]=floor(pow(bucketBase, bucketSlot), 1),\n    counts=iff(isnull(count_), 0, count_)\n| summarize Count=sum(counts) by [\"Duration (ms)\"]\n| where ['Duration (ms)'] >= todouble(minDuration)\n| order by [\"Duration (ms)\"] asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "$dependency Dependencies (count)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\ndependencies\n| where $__timeFilter(timestamp)\n// additional filters can be applied here\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| count\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Number of failed dependencies matching $dependency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n| where success == false\n| count\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top Dependencies by Avg Duration",
   "type": "table",
   "description": "Click on a dependency name to filter dashboard.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "set truncationmaxrecords=10000;set truncationmaxsize=67108864; \nlet m = dependencies\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"  \n| project itemCount, duration, typeTransform=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), targetTransform=tostring(split(target, \" | cid-v1\")[0]), name, type, target;\nm\n| summarize Count=sum(itemCount), Avg=sum(itemCount * duration) / sum(itemCount)\n| project [\"Dependency name\"]=\"All\", Avg, Count\n| union(\nm\n| summarize Count=sum(itemCount), Avg=sum(itemCount * duration) / sum(itemCount) by typeTransform=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), targetTransform=tostring(split(target, \" | cid-v1\")[0]), name, target, type\n| sort by Avg desc\n| project [\"Dependency name\"]=strcat(typeTransform, \": \", name , \" \", targetTransform), Avg, Count, type, target, name)\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 20 Dependencies matching $dependency by Relevance",
   "type": "table",
   "description": "Click on the OperationID or dependency name to open the trace details in explorer",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 42 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let minDuration = iif(isempty(\"$min_duration\"), \"0\", \"$min_duration\");\nlet maxDuration = iif(isempty(\"$max_duration\"), \"0\", \"$max_duration\");\n\nlet min_length_8 = (s: string) {\n    let len = strlen(s);\n    case(len == 1, strcat(s, s, s, s, s, s, s, s),\n        len == 2 or len == 3, strcat(s, s, s, s),\n        len == 4 or len == 5 or len == 6 or len == 7, strcat(s, s),\n        s)\n};\nlet ai_hash = (s: string) {\n    abs(toint(__hash_djb2(min_length_8(s))))\n};\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| extend typeTransform=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), targetTransform=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(typeTransform, \": \", name, \" \", targetTransform)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| where duration >= todouble(minDuration) and duration <= todouble(maxDuration)\n//| where returncode in ($return_code)\n| project [\"Dependency Name\"], target, ResponseCode = resultCode, ResponseTime = duration, OperationID = operation_Id, Score=ai_hash(operation_Id), type, name\n| top 20 by Score asc\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}