{
 "title": "Azure / Insights / Applications - Failures - 2. Dependencies",
 "description": "The dashboard provides insights of dependency failures through Application Insights.",
 "tags": [ "Azure-AppInsights-Failures" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {}
   },
   { "name": "res", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" },
   {
    "name": "dependency",
    "label": "Dependency",
    "query": {}
   },
   {
    "name": "dependency_result_code",
    "label": "Result Code",
    "query": {}
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "# Failures - Dependencies" } },
  {
   "title": "Application Insights - Failures - Dependencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Failed Dependencies (count)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "dependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where \"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code)\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| summarize FailedCount=sumif(itemCount, success == false) by bin(timestamp, $__interval)\n| order by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top response codes (count)",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 3 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "dependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where success == false\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| summarize Count=sum(itemCount) by [\"Result Code\"]=resultCode\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Server Requests (count)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n// calculate average request duration for all requests\n| summarize Count = count() by bin(timestamp, $__interval)\n| order by timestamp asc\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Response codes (count)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 13 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "dependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| where \"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code)\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| summarize ResultCode = sum(itemCount) by resultCode, bin(timestamp, $__interval)\n| sort by timestamp asc\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "time_series"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "All Failed dependencies (Count)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "dependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| summarize failedCount=sumif(itemCount, success == false)\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failed dependencies matching result code and dependency",
   "type": "stat",
   "description": "Failed dependencies matching result code ${dependency_result_code:text} and dependency ${dependency:text}",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "dependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp)\n| where \"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code)\n| where client_Type != \"Browser\"\n| extend type=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), target=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(type, \": \", name, \" \", target)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency))\n| summarize failedCount=sumif(itemCount, success == false)\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top Dependencies by Avg Duration",
   "type": "table",
   "description": "Click on a dependency name to filter dashboard.",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let m = dependencies\n| where $__timeFilter(timestamp)\n| where client_Type != \"Browser\"\n| project itemCount, duration, typeTransform=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), targetTransform=tostring(split(target, \" | cid-v1\")[0]), name, type, target, user_Id, success, resultCode;\nm\n| summarize [\"Failed count\"]=sumif(itemCount, success == false and  (\"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code))), [\"Impacted users\"]=dcountif(user_Id, success == false and  (\"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code))), [\"Total count\"]=sum(itemCount)\n| project [\"Dependency name\"]=\"All\", [\"Failed count\"], [\"Impacted users\"], [\"Total count\"]\n| union(\nm\n| summarize [\"Failed count\"]=sumif(itemCount, success == false and  (\"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code))), [\"Impacted users\"]=dcountif(user_Id, success == false and  (\"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code))), [\"Total count\"]=sum(itemCount) by typeTransform=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), targetTransform=tostring(split(target, \" | cid-v1\")[0]), name, target, type\n| where [\"Failed count\"] > 0\n| sort by [\"Failed count\"] desc\n| project [\"Dependency name\"]=strcat(typeTransform, \": \", name , \" \", targetTransform), [\"Failed count\"], [\"Total count\"], [\"Impacted users\"], type, target, name)\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Top 20 Dependencies matching $dependency by Relevance",
   "type": "table",
   "description": "Click on an OperationID or Dependency name to view the trace details in explorer.",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 22 },
   "targets": [
    {
     "azureLogAnalytics": {
      "query": "let min_length_8 = (s: string) {\n    let len = strlen(s);\n    case(len == 1, strcat(s, s, s, s, s, s, s, s),\n        len == 2 or len == 3, strcat(s, s, s, s),\n        len == 4 or len == 5 or len == 6 or len == 7, strcat(s, s),\n        s)\n};\nlet ai_hash = (s: string) {\n    abs(toint(__hash_djb2(min_length_8(s))))\n};\n\ndependencies\n// additional filters can be applied here\n| where $__timeFilter(timestamp) and  (\"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code))\n| extend typeTransform=iff(tolower(type) == \"http (tracked component)\", \"HTTP\", type), targetTransform=tostring(split(target, \" | cid-v1\")[0])\n| extend [\"Dependency Name\"] = strcat(typeTransform, \": \", name, \" \", targetTransform)\n| where (\"All\" in ($dependency) or [\"Dependency Name\"] in ($dependency)) and isnotempty(operation_Id)\n| where (\"All\" in ($dependency_result_code) or resultCode in ($dependency_result_code))\n| project [\"Dependency Name\"], target, ResponseCode = resultCode, ResponseTime = duration, OperationID = operation_Id, type, name, Score=ai_hash(operation_Id)\n| top 20 by Score asc\n\n\n",
      "resources": [
       "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$res"
      ],
      "resultFormat": "table"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}