{
 "title": "Azure / Infrastructure / Apps Monitoring",
 "description": "This dashboard displays traffic-light indicators to show the health of your Azure infrastructure resources based on key performance indicators and thresholds defined for each infrastructure resource type.  The KPIs and thresholds come from Azure Monitor Baseline Alerts (https://azure.github.io/azure-monitor-baseline-alerts/).  \n\nPrerequisites:\nThe queries used in the dashboard require that you have resource metrics being sent to a Log Analytics Workspace. The AzureMetrics and AzureDiagnostics tables are required.  This can be achieved through a resource’s diagnostic settings. For detailed instructions, refer to Azure Monitor Essentials: Diagnostic Settings:  https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings#metrics\n\nInstallation and Configuration:\nThis dashboard requires the JSON API Grafana plugin and a configured data source for Azure Monitor Baseline Alerts.  Follow these steps to install and configure the JSON API plugin:\n\n1.  Navigate to Connections->Connect Data.\n2.  Search for “JSON API” and then select the JSON API data source.\n3.  Install the plugin if it is not already installed.\n4.  On the JSON API plugin page, click “Create a JSON API data source\".\n5.  On the create JSON API page, give it the name “AMBA” and for the URL, give it the value:  https://raw.githubusercontent.com/Azure/azure-monitor-baseline-alerts/main/visualizations/grafana/infra-monitoring-amba-thresholds.json \n6.  Click the Save & test button. You should see a green checkbox and Success message if configured correctly.\n\nThis is one of a collection of dashboards linked together via dashboard links and the \"azure-infra-monitor\" tag.  Other dashboards in the collection include:\nAzure / Infrastructure / Network Monitoring\nAzure / Infrastructure / Storage and Key Vaults Monitoring\nAzure / Infrastructure / Compute Monitoring\nAzure / Infrastructure / Data Monitoring\n\nThe other dashboards in this collection can be found in the Azure Monitor Team Grafana library here:  https://grafana.com/orgs/azuremonitorteam/dashboards.  Once imported, you will be able to access these dashboards using the Azure Infra Monitoring Dashboards tab. ",
 "tags": [ "azure-infra-monitor" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "amba", "label": "Azure Monitor Baseline Alerts", "query": "marcusolsson-json-datasource" },
   {
    "name": "subsWSScope",
    "label": "Workspace Scope",
    "query": {}
   },
   {
    "name": "laws",
    "label": "Workspaces",
    "query": {}
   },
   {
    "name": "subsRESScope",
    "label": "Resource Scope",
    "query": {}
   },
   {
    "name": "healthy_color",
    "query": "\"rgb(45\\,161\\,55)\""
   },
   {
    "name": "warning_color",
    "query": "\"rgb(222\\,210\\,38)\""
   },
   {
    "name": "unhealthy_color",
    "query": "\"rgb(255\\,31\\,46)\""
   },
   {
    "name": "amba_webapp_HttpResponseTime",
    "query": {}
   },
   {
    "name": "amba_webapp_CpuTime",
    "query": {}
   },
   {
    "name": "amba_webapp_PrivateBytes",
    "query": {}
   },
   {
    "name": "amba_webapp_RequestsInApplicationQueue",
    "query": {}
   },
   {
    "name": "amba_AKS_node_cpu_usage_percentage",
    "query": {}
   },
   {
    "name": "amba_AKS_node_memory_working_set_percentage",
    "query": {}
   },
   {
    "name": "amba_AKS_node_disk_usage_percentage",
    "query": {}
   },
   {
    "name": "amba_AKS_cluster_autoscaler_unsched_pods_count",
    "query": {}
   },
   {
    "name": "amba_ACR_StorageUsed",
    "query": {}
   },
   {
    "name": "amba_Redis_percentProcessorTime",
    "query": {}
   },
   {
    "name": "amba_Redis_usedmemorypercentage",
    "query": {}
   },
   {
    "name": "amba_Redis_cacheLatency",
    "query": {}
   },
   {
    "name": "amba_Redis_errors",
    "query": {}
   },
   {
    "name": "amba_ServiceBus_UserErrors",
    "query": {}
   },
   {
    "name": "amba_ServiceBus_ServerErrors",
    "query": {}
   },
   {
    "name": "amba_ServiceBus_ThrottledRequests",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<p style=\"font-size:24px;color:rgb(87, 148, 242);\">Azure Infrastructure Monitoring Dashboard (Apps)</p>\n\r\nSelect a data source, workspace scope, workspace(s) and resource scope.   \r\nExamine the key performance indicators for your resources by expanding the row for a resource type.  \r\nRecommended KPIs and thresholds used in this dashboard come from [Azure Monitor Baseline Alerts](https://azure.github.io/azure-monitor-baseline-alerts/).  \r\nSee dashboard description for more details on linking to other Infrastructure Monitor dashboards.\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<br>\n\r\nKey:\n- Green\\Healthy &nbsp;- None of the resources of that resource type have KPIs that are exceeding thresholds.\n- Yellow\\Warning - At least one resource of that resource type has one KPI exceeding a threshold.\n- Red\\Unhealthy &nbsp;- At least one resource of that resource type has two or more KPIs exceeding a threshold."
   }
  },
  {
   "title": "Web Apps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\n| where _ResourceId has '/microsoft.web/sites/'\n| where SubscriptionId has_any ($subsRESScope)\n| where MetricName in('HttpResponseTime', 'CpuTime', 'PrivateBytes', 'RequestsInApplicationQueue' )\n| summarize\n  kpi1 = avgif(Total, MetricName == 'HttpResponseTime'),\n  kpi2 = avgif(Total, MetricName == 'CpuTime'),\n  kpi3 = avgif(Total, MetricName == 'PrivateBytes'),\n  kpi4 = avgif(Total, MetricName == 'RequestsInApplicationQueue') by _ResourceId, Resource\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\n|extend health1 = iff(kpi1>$amba_webapp_HttpResponseTime, 1, 0)\n|extend health2 = iff(kpi2>$amba_webapp_CpuTime, 1, 0)\n|extend health3 = iff(kpi3>$amba_webapp_PrivateBytes, 1, 0)\n|extend health4 = iff(kpi4>$amba_webapp_RequestsInApplicationQueue, 1, 0)\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\n|extend health = health1 + health2 + health3 + health4\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "AKS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\n| where _ResourceId has '/microsoft.containerservice/managedclusters/'\n| where SubscriptionId has_any ($subsRESScope)\n| where MetricName in('node_cpu_usage_percentage', 'node_memory_working_set_percentage', 'node_disk_usage_percentage', 'cluster_autoscaler_unschedulable_pods_count' )\n| summarize\n  kpi1 = avgif(Average, MetricName == 'node_cpu_usage_percentage'),\n  kpi2 = avgif(Average, MetricName == 'node_memory_working_set_percentage'),\n  kpi3 = avgif(Average, MetricName == 'node_disk_usage_percentage'),\n  kpi4 = avgif(Average, MetricName == 'cluster_autoscaler_unschedulable_pods_count') by _ResourceId, Resource\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\n|extend health1 = iff(kpi1>$amba_AKS_node_cpu_usage_percentage, 1, 0)\n|extend health2 = iff(kpi2>$amba_AKS_node_memory_working_set_percentage, 1, 0)\n|extend health3 = iff(kpi3>$amba_AKS_node_disk_usage_percentage, 1, 0)\n|extend health4 = iff(kpi4>$amba_AKS_cluster_autoscaler_unsched_pods_count, 1, 0)\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\n|extend health = health1 + health2 + health3 + health4\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Container Registries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\n| where _ResourceId has '/microsoft.containerregistry/registries/'\n| where SubscriptionId has_any ($subsRESScope)\n| where MetricName in('StorageUsed')\n| summarize\n  kpi1 = avgif(Total, MetricName == 'StorageUsed') by _ResourceId, Resource\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\n|extend health1 = iff(kpi1>$amba_ACR_StorageUsed, 1, 0)\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\n|extend health = health1\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Redis Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureMetrics\n| where _ResourceId has 'microsoft.cache/redis'\n| where SubscriptionId has_any ($subsRESScope)\n| where MetricName in('percentProcessorTime', 'usedmemorypercentage', 'cacheLatency', 'errors' )\n| summarize\n  kpi1 = avgif(Average, MetricName == 'percentProcessorTime'),\n  kpi2 = avgif(Average, MetricName == 'usedmemorypercentage'),\n  kpi3 = avgif(Average, MetricName == 'cacheLatency'),\n  kpi4 = avgif(Maximum, MetricName == 'errors') by _ResourceId, Resource\n|extend kpi1 = iff(isnan(kpi1), 0.0, kpi1)\n|extend kpi2 = iff(isnan(kpi2), 0.0, kpi2) \n|extend kpi3 = iff(isnan(kpi3), 0.0, kpi3)\n|extend kpi4 = iff(isnan(kpi4), 0.0, kpi4)\n|extend health1 = iff(kpi1>$amba_Redis_percentProcessorTime, 1, 0)\n|extend health2 = iff(kpi2>$amba_Redis_usedmemorypercentage, 1, 0)\n|extend health3 = iff(kpi3>$amba_Redis_cacheLatency, 1, 0)\n|extend health4 = iff(kpi4>$amba_Redis_errors, 1, 0)\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\n|extend h4color = iff(tobool(health4), $unhealthy_color, $healthy_color)\n|extend health = health1 + health2 + health3 + health4\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\n| order by health desc ",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  {
   "title": "Service Bus",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": true,
      "query": "AzureDiagnostics\n| where _ResourceId has '/microsoft.servicebus/namespaces/'\n| where SubscriptionId has_any ($subsRESScope)\n| where Category == \"DiagnosticErrorLogs\"\n| summarize\n  kpi1 = countif(OperationResult_s =~ \"ClientError\"), \n  kpi2 = countif(OperationResult_s =~ \"ServerBusy\"),\n  kpi3 = countif(OperationResult_s =~ \"QuotaExceeded\") by _ResourceId, Resource\n|extend kpi1 = iff(isnan(toreal(kpi1)), 0.0, toreal(kpi1))\n|extend kpi2 = iff(isnan(toreal(kpi2)), 0.0, toreal(kpi2)) \n|extend kpi3 = iff(isnan(toreal(kpi3)), 0.0, toreal(kpi3))\n|extend health1 = iff(kpi1>$amba_ServiceBus_UserErrors, 1, 0)\n|extend health2 = iff(kpi2>$amba_ServiceBus_ServerErrors, 1, 0)\n|extend health3 = iff(kpi3>$amba_ServiceBus_ThrottledRequests, 1, 0)\n|extend h1color = iff(tobool(health1), $unhealthy_color, $healthy_color)\n|extend h2color = iff(tobool(health2), $unhealthy_color, $healthy_color)\n|extend h3color = iff(tobool(health3), $unhealthy_color, $healthy_color)\n|extend health = health1 + health2 + health3\n|extend hcolor = iff(health>1, $unhealthy_color, iff(health==1, $warning_color, $healthy_color))\n| order by health desc",
      "resources": [ "$laws" ],
      "resultFormat": "logs",
      "timeColumn": "TimeGenerated"
     },
     "subscriptions": [
      "ebb79bc0-aa86-44a7-8111-cabbe0c43993"
     ]
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Web Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Web App Response Time",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    },
    {
     "title": "Web App CPU Time",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    },
    {
     "title": "Web App Private Bytes",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    },
    {
     "title": "Web App Requests in Queue",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 104 }
     ]
    }
   ]
  },
  {
   "title": "AKS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "AKS Node CPU Usage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 110 }
     ]
    },
    {
     "title": "AKS Node Memory Working Set Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 110 }
     ]
    },
    {
     "title": "AKS Node Disk Usage Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 110 }
     ]
    },
    {
     "title": "AKS Unscheduled Pods Count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 110 }
     ]
    }
   ]
  },
  {
   "title": "Container Registries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container Registry Storage Used",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 111 }
     ]
    }
   ]
  },
  {
   "title": "Redis Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Cache Percent Processor Time",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 112 }
     ]
    },
    {
     "title": "Redis Cache Used Memory Percentage",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 112 }
     ]
    },
    {
     "title": "Redis Cache Cache Latency",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 112 }
     ]
    },
    {
     "title": "Redis Cache Errors",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 112 }
     ]
    }
   ]
  },
  {
   "title": "Service Bus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Bus User Errors",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 113 }
     ]
    },
    {
     "title": "Service Bus Server Errors",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 6, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 113 }
     ]
    },
    {
     "title": "Service Bus Throttled Requests",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 6, "x": 12, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "panelId": 113 }
     ]
    }
   ]
  }
 ]
}