{
 "title": "Azure / Insights / Networks",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "loadbalancer",
    "label": "Namespaces",
    "query": {}
   },
   {
    "name": "applicationgateway",
    "query": {}
   },
   {
    "name": "trafficmanager",
    "query": {}
   },
   {
    "name": "frontdoor",
    "query": {}
   },
   {
    "name": "resloadbalancer",
    "label": "Load Balancers",
    "query": {}
   },
   {
    "name": "resapplicationgateway",
    "label": "Application Gateways",
    "query": {}
   },
   {
    "name": "restrafficmanager",
    "label": "Traffic Managers",
    "query": {}
   },
   {
    "name": "resfrontdoor",
    "label": "Front doors",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Front Door - ${resfrontdoor}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "resfrontdoor" },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resfrontdoor)\n| project Name=name, sku.name, location, subscriptionId\n| join kind=inner(\n    resourcecontainers\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\n        | project subscriptionId, Subscription = name\n) on subscriptionId\n| project-away subscriptionId, subscriptionId1\n| join kind=leftouter(\n    alertsmanagementresources\n        | where tolower(properties.context.context.resourceName) == tolower($resfrontdoor)\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\n        | project properties_context_context_resourceName, count_, subscriptionId\n) on $left.Name == $right.properties_context_context_resourceName\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\n"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Origin Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "OriginLatency",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "RequestCount",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "TotalLatency",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Origin Health Percentage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$frontdoor",
      "metricName": "OriginHealthPercentage",
      "metricNamespace": "$frontdoor",
      "resourceGroup": "$rg",
      "resourceName": "$resfrontdoor",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Traffic Manager - ${restrafficmanager}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "restrafficmanager"
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($restrafficmanager)\n| project Name=name, sku.name, location, subscriptionId\n| join kind=inner(\n    resourcecontainers\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\n        | project subscriptionId, Subscription = name\n) on subscriptionId\n| project-away subscriptionId, subscriptionId1\n| join kind=leftouter(\n    alertsmanagementresources\n        | where tolower(properties.context.context.resourceName) == tolower($restrafficmanager)\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\n        | project properties_context_context_resourceName, count_, subscriptionId\n) on $left.Name == $right.properties_context_context_resourceName\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\n"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Endpoint Status by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$trafficmanager",
      "metricName": "ProbeAgentCurrentEndpointStateByProfileResourceId",
      "metricNamespace": "$trafficmanager",
      "resourceGroup": "$rg",
      "resourceName": "$restrafficmanager",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Queries by Endpoint Returned",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "$trafficmanager",
      "metricName": "QpsByEndpoint",
      "metricNamespace": "$trafficmanager",
      "resourceGroup": "$rg",
      "resourceName": "$restrafficmanager",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Application Gateways - ${resapplicationgateway}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "resapplicationgateway"
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resapplicationgateway)\n| project Name=name, sku.name, location, subscriptionId\n| join kind=inner(\n    resourcecontainers\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\n        | project subscriptionId, Subscription = name\n) on subscriptionId\n| project-away subscriptionId, subscriptionId1\n| join kind=leftouter(\n    alertsmanagementresources\n        | where tolower(properties.context.context.resourceName) == tolower($resapplicationgateway)\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\n        | project properties_context_context_resourceName, count_, subscriptionId\n) on $left.Name == $right.properties_context_context_resourceName\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\n"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$applicationgateway",
      "metricName": "Throughput",
      "metricNamespace": "$applicationgateway",
      "resourceGroup": "$rg",
      "resourceName": "$resapplicationgateway",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Unhealthy Host Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$applicationgateway",
      "metricName": "UnhealthyHostCount",
      "metricNamespace": "$applicationgateway",
      "resourceGroup": "$rg",
      "resourceName": "$resapplicationgateway",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$applicationgateway",
      "metricName": "FailedRequests",
      "metricNamespace": "$applicationgateway",
      "resourceGroup": "$rg",
      "resourceName": "$resapplicationgateway",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$applicationgateway",
      "metricName": "ResponseStatus",
      "metricNamespace": "$applicationgateway",
      "resourceGroup": "$rg",
      "resourceName": "$resapplicationgateway",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Load Balancers - ${resloadbalancer}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "resloadbalancer"
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "resources\n| where tolower(subscriptionId) == tolower(\"$sub\") and tolower(resourceGroup) == tolower(\"$rg\") and tolower(name) == tolower($resloadbalancer)\n| project Name=name, sku.name, location, subscriptionId\n| join kind=inner(\n    resourcecontainers\n        | where type == \"microsoft.resources/subscriptions\" and tolower(subscriptionId) == tolower(\"$sub\")\n        | project subscriptionId, Subscription = name\n) on subscriptionId\n| project-away subscriptionId, subscriptionId1\n| join kind=leftouter(\n    alertsmanagementresources\n        | where tolower(properties.context.context.resourceName) == tolower($resloadbalancer)\n        | summarize count() by tostring(properties.context.context.resourceName), subscriptionId\n        | project properties_context_context_resourceName, count_, subscriptionId\n) on $left.Name == $right.properties_context_context_resourceName\n| project Name, Alerts=iff(isnull(count_), 0, count_), SKU=tostring(sku_name), Subscription, Location=location\n"
     },
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "SYN Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$loadbalancer",
      "metricName": "SYNCount",
      "metricNamespace": "$loadbalancer",
      "resourceGroup": "$rg",
      "resourceName": "$resloadbalancer",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "SNAT Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "$loadbalancer",
      "metricName": "SnatConnectionCount",
      "metricNamespace": "$loadbalancer",
      "resourceGroup": "$rg",
      "resourceName": "$resloadbalancer",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Data Path Availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$loadbalancer",
      "metricName": "VipAvailability",
      "metricNamespace": "$loadbalancer",
      "resourceGroup": "$rg",
      "resourceName": "$resloadbalancer",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Health Probe Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "dimensionFilters": [],
      "metricDefinition": "$loadbalancer",
      "metricName": "DipAvailability",
      "metricNamespace": "microsoft.network/loadbalancers",
      "resourceGroup": "$rg",
      "resourceName": "$resloadbalancer",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  }
 ]
}